apiVersion: banana.mdlwr.se/v1alpha1
kind: Layer
metadata:
  name: nginx-default-wildcard-certificate
spec:
  match:
    name: nginx-ingress-controller
    repo: https://charts.bitnami.com/bitnami
  values:
    extraArgs:
      default-ssl-certificate: $(POD_NAMESPACE)/vgr-wildcard-cert