## Append samples of your project ##
resources:
- banana_v1alpha1_featureset.yaml
- banana_v1alpha1_feature.yaml
- banana_v1alpha1_featureoverride.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
